all:
	@python3 -m main

lr:
	@python3 -m logistic_regression.main

describe:
	@python3 -m data_analysis.main

histogram:
	@python3 -m data_visualization.histogram

scatter_plot:
	@python3 -m data_visualization.scatter_plot

pair_plot:
	@python3 -m data_visualization.pair_plot

training:
	@python3 -m data_visualization.training_board

.PHONY: describe histogram scatter_plot pair_plot
