all:
	@echo "No idea"

describe:
	@python -m data_analysis.main

histogram:
	@python -m data_visualization.histogram

scatter_plot:
	@python -m data_visualization.scatter_plot

pair_plot:
	@python -m data_visualization.pair_plot